#!/bin/sh

echo "##################################################"
# TODO for new maintainers using the template generator:
# replace [example-project] with an more specific use case
# in sluggified form. (e.g. nodejs-yarn or python3-setup-pyenv)
echo "Code Server Bootstrapper for Linode for [example-project]"
# TODO for new maintainrrs using the template generator:
# replace [@AndreiJirohHaliliDev2006] with your GitHub username
echo "Written with love by [@AndreiJirohHaliliDev2006] and contributors"
echo "########################################"

# install code-server service system-wide
echo "==> Installing code-server globally..."
export HOME=/root
curl -fsSL https://code-server.dev/install.sh | sh

# add our helper server to redirect to the proper URL for --link
echo "==> Downloading helper tools for proper URL redirection..."
git clone https://github.com/bpmct/coder-cloud-redirect-server
cd coder-cloud-redirect-server
cp coder-cloud-redirect.service /etc/systemd/system/
cp coder-cloud-redirect.py /usr/bin/

# create a code-server user
echo "==> Creating user coder with sudo permissions..."
adduser --disabled-password --gecos "" coder
echo "coder ALL=(ALL:ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/coder
usermod -aG sudo coder

############################################################
# Add your tools your users want to install on an fresh machine here ⬇

# TODO for new maintainers using the template generator:
# replace [example-project] with an more specific use case
# in sluggified form. (e.g. nodejs-yarn or python3-setup-pyenv)
echo "==> Installing tools for [example-project]"

# For userland installs, like Node Version Manager,
# you may need to prefix "su coder" before the command.
# To keep things shorter, we made an alias you cannot
# refuse for userland installs.
# For global installs, nuke the sudo part since we're root

# sudo -u coder might be an nice option, but since we're
# root, we don't need to re-enter our password
alias userland-install="su coder"

# Cloudflared
# install Cloudflared
wget -q https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-linux-amd64.deb \
    && dpkg -i cloudflared-stable-linux-amd64.deb

# croc
curl https:/getcroc.schollz.com | sudo sh

# rclone? (we commented out, but you can add back)
# sudo apt-get update && sudo apt-get install unzip -y
# curl https://rclone.org/install.sh | sudo bash

# Docker/Podman and Kubernetes?
# note: scripts.madebythepins.tk is WIP and usually point
# to gh:MadeByThePinsHub/scripts.madebythepins.tk
# repository.
# curl https://scripts.madebythepins.tk/install/docker-cdrs | bash
# curl https://scripts.madebythepins.tk/install/podman-cdrs | bash
# curl https://scripts.madebythepins.tk/install/k8s-cdrs | bash

# Add your tools your users want to install on an fresh machine here ⬆
############################################################

# copy ssh keys from root
cp -r /root/.ssh /home/coder/.ssh
chown -R coder:coder /home/coder/.ssh

# configure code-server to use --link with the "coder" user
echo "==> Enabling code-server and cloud-redirect..."
mkdir -p /home/coder/.config/code-server
touch /home/coder/.config/code-server/config.yaml
echo "link: true" > /home/coder/.config/code-server/config.yaml
chown -R coder:coder /home/coder/.config

# start and enable code-server and our helper service
systemctl enable --now code-server@coder
systemctl enable --now coder-cloud-redirect

echo "You're now ready to rumble! Check the logs for the link with:"
echo "   systemctl status code-server@coder"
echo "Having coding-slash-cloud developing!"

