#!/bin/sh

echo "##################################################"
# TODO for new maintainers using the template generator:
# replace [example-project] with an more specific use case
# in sluggified form. (e.g. nodejs-yarn or python3-setup-pyenv)
echo "Code Server Bootstrapper for Linode for [example-project]"
# TODO for new maintainrrs using the template generator:
# replace [@AndreiJirohHaliliDev2006] with your GitHub username
echo "Written with love by [@AndreiJirohHaliliDev2006] and contributors"
echo "########################################"

# allow us to access systemd logs to see the status of --link
echo "==> Configuring systemd to store logs in /var/log/journal..."
sed -i.bak 's/#Storage=auto/Storage=persistent/' /etc/systemd/journald.conf
mkdir -p /var/log/journal
systemctl force-reload systemd-journald
systemctl restart systemd-journald

# install code-server service system-wide
echo "==> Installing code-server globally..."
export HOME=/root
curl -fsSL https://code-server.dev/install.sh | sh

# add our helper server to redirect to the proper URL for --link
echo "==> Downloading helper tools for proper URL redirection..."
git clone https://github.com/bpmct/coder-cloud-redirect-server
# shellcheck disable=SC2164
cd coder-cloud-redirect-server
cp coder-cloud-redirect.service /etc/systemd/system/
cp coder-cloud-redirect.py /usr/bin/

# create a code-server user
echo "==> Creating user coder with sudo permissions..."
adduser --disabled-password --gecos "" coder
echo "coder ALL=(ALL:ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/coder
usermod -aG sudo coder

############################################################
# Add your tools your users want to install on an fresh machine here ⬇

# TODO for new maintainers using the template generator:
# replace [example-project] with an more specific use case
# in sluggified form. (e.g. nodejs-yarn or python3-setup-pyenv)
echo "==> Installing tools for [example-project]"

# For userland installs, like Node Version Manager,
# you may need to prefix "su coder" before the command.
# To keep thongs shorter, we made an alias you cannot
# refuse for userland installs.
# For global installs, nuke the sudo part since we're root

# sudo -u coder might be an nice option, but since we're
# root, we don't need to re-enter our password
alias userland-install="su coder"

# Cloudflared
# install Cloudflared
wget -q https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-linux-amd64.deb \
    && sudo dpkg -i cloudflared-stable-linux-amd64.deb

# croc
curl https:/getcroc.schollz.com | sudo sh

# rclone? (we commented out, but you can add back)
# sudo apt-get update && sudo apt-get install unzip -y
# curl https://rclone.org/install.sh | sudo bash

# Docker/Podman and Kubernetes?
# note: scripts.madebythepins.tk is WIP and usually point
# to gh:code-server-boilerplates/scripts.madebythepins.tk
# repository.
# curl https://scripts.madebythepins.tk/install/docker-cdrs | bash
# curl https://scripts.madebythepins.tk/install/podman-cdrs | bash
# curl https://scripts.madebythepins.tk/install/k8s-cdrs | bash

# Add your tools your users want to install on an fresh machine here ⬆
############################################################

# copy ssh keys from root
echo "==> Copying SSH keys from root to coder..."
cp -r /root/.ssh /home/coder/.ssh
chown -R coder:coder /home/coder/.ssh

# use a more unique hostname (for Linode)
# comment these lines out if you don't want
echo "==> Changing hostname into linode-$LINODE_ID"
sudo hostnamectl set-hostname "linode-$LINODE_ID"
# shellcheck disable=SC1091
. "/root/.bashrc"

# configure code-server to use --link with the "coder" user
echo "==> Telling the server to use the link flag by default..."
mkdir -p /home/coder/.config/code-server
touch /home/coder/.config/code-server/config.yaml
echo "link: true" > /home/coder/.config/code-server/config.yaml
chown -R coder:coder /home/coder/.config

# start and enable code-server and our helper service
echo "==> Enabling code-server and cloud-redirect..."
systemctl enable --now code-server@coder
systemctl enable --now coder-cloud-redirect

echo "info: You're now ready to rumble! Check the logs if it's ready to receive traffic:"
echo "info:      systemctl status code-server@coder"
echo "info: Having coding!"
